name: Build and Deploy Docker Image to S3

on:
  push:
    branches:
      - master

env:
  S3_BUCKET_NAME: ${{ secrets.DEPLOY_S3_BUCKET_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t wihao-image:latest .

      - name: Save Docker image as tar
        run: docker save -o wihao-image.tar wihao-image:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload image to S3 bucket
        uses: aws-actions/amazon-s3-upload@v2
        with:
          aws-region: ap-northeast-2
          bucket-name: $S3_BUCKET_NAME
          object-key: wihao-image.tar
          file-path: wihao-image.tar
